#!/bin/sh
OSBRAND=`cat /etc/os-release | grep -i Name | head -1 | cut -f2 -d=`
# /bin/chmod +s /sbin/mount.cifs
case $OSBRAND in
     '"Raspbian"'|'"Ubuntu"'|Raspbian|Ubuntu)
        /usr/bin/apt-get update
        /usr/bin/apt-get -y upgrade
        /usr/bin/apt-get -y clean
        /usr/bin/apt-get -y --purge autoremove
     ;;
     Fedora|"Fedora")
        /usr/bin/dnf update
        /usr/bin/dnf autoremove --skip-broken
     ;;
     *)
        /usr/bin/yum -y update
     ;;
esac
