#!/bin/bash
# Source: https://askubuntu.com/questions/5417/how-to-get-the-gpu-info
OS=`uname`
case $OS in
	Linux)
		if ! [ $LOGNAME = "root" ]; then
                        echo "Need to be root"
                else
		        GPU=$(lspci | grep VGA | cut -d ":" -f3)
			RAM=$(cardid=$(lspci | grep VGA |cut -d " " -f1);lspci -v -s $cardid | grep " prefetchable"| cut -d "=" -f2)
			echo $GPU $RAM
		fi
	;;
esac	
